#!/usr/bin/env bash
#
# JAVA_HOME is set in the init script by gradle
#
export JAVA_HOME='JAVAHOME'
echo "Checking if code is properly formatted"
if ! ./gradlew.bat spotlessCheck &> /dev/null; then
    echo "Code is not formatted correctly, formatting code"
    ./gradlew.bat spotlessApply
	echo "Finished formatting code"
	echo "Please review code changes and commit again"
	exit 1
else
  echo "Code is properly formatted"
fi